### ISSUE TITLE
No data received when running `npm start` outside of contract-kit

### ISSUE THREAD

**Issue by daviddao** [oasislabs/game-box#15]
Using MacOS and running `npm start` outside of contract-kit I can't access `localhost` via Chrome when deploying with `--network oasis`. To fix this issue, I had to enter contract-kit via port forwarding: `docker run -ti --rm -v "$PWD":/project -p8545:8545 -p8546:8546 -p8080:8080 oasislabs/contract-kit:latest /bin/bash` and run `npm start` within the container.

**Comment by clementfung** [comment]
Thanks for the feedback! 
I updated the README, it's safer to just assume `npm start` is run from within contract-kit.
